services:
  # Backend Service Setup
  realestate.backend:
    container_name: realestate.backend
    build:
      context: ./backend
      dockerfile: RealEstate/RealEstate/Dockerfile
    ports:
      - 8001:8081
      - 8002:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=your-cert-password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl/dev-cert.pfx
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - realestate-dev-network
    depends_on:
      - realestate.redis
      - realestate.redis-insigh
      - realestate.sqlserver
      - realestate.rabbit-mq
    restart: unless-stopped

  # Frontend Service Setup
  realestate.frontend:
    container_name: realestate.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - realestate-dev-network
    depends_on:
      - realestate.backend

  # Redis Service Setup
  realestate.redis:
    container_name: realestate.redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - realestate-dev-network

  # Redis Insight for Redis UI Service
  realestate.redis-insigh:
    container_name: realestate.redis-insight
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - realestate-dev-network

  # Rabbit MQ Service Setup
  realestate.rabbit-mq:
    container_name: realestate.rabbit-mq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - realestate-dev-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s # Reduced interval
      timeout: 30s
      retries: 20 # Increased retries
      start_period: 60s # Give more time to start

  # SQL Server Setup
  realestate.sqlserver:
    container_name: realestate.sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "Sql!2345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - realestate-dev-network

# Networks for communication
networks:
  realestate-dev-network:
    driver: bridge

# volumes for persistant data
volumes:
  redis-data:
  rabbitmq_data:
  sqlserver_data:
